### ISSUE TITLE
Php trigger notice if route not defined

### ISSUE THREAD

**Issue by Ekstazi** [MitinSany/test_skysilk#1]
https://github.com/MitinSany/test_skysilk/blob/4b11b7f31c39a070b4f59948a834f38ac277c5d4/app/Application.php#L73

**Comment by MitinSany** [comment]
This case already present in code
https://github.com/MitinSany/test_skysilk/blob/4b11b7f31c39a070b4f59948a834f38ac277c5d4/app/Application.php#L84
